### ISSUE TITLE
syntax error in integrated_features_exraction.py

### ISSUE THREAD

**Issue by iikmuhamadmalikmatin** [urwithajit9/ClaMP#4]
I changed the` source_path, output_file, label, peid.yara` path. and run the `integrated_features_exraction.py` code. but I get an error message here :

```
Traceback (most recent call last):
  File "integrated_features_extraction.py", line 375, in <module>
    main()
  File "integrated_features_extraction.py", line 372, in main
    features.create_dataset()
  File "integrated_features_extraction.py", line 356, in create_dataset
    data = self.extract_all(filepath)
  File "integrated_features_extraction.py", line 330, in extract_all
    packer = self.check_packer(filepath)
  File "integrated_features_extraction.py", line 239, in check_packer
    result.append([1,matches['main'][0]['rule']])
TypeError: list indices must be integers, not str
```
is there anywrong with the syntax ? i cant find the solution..
thank you..

**Comment by urwithajit9** [comment]
Thanks for raising the issue. 
it is now resolved. The problem was with the Yara module's match() method, earlier it returns a dict{} but now the return is a list.
Please try the updated script and let me know if the issue is resolved.

**Comment by iikmuhamadmalikmatin** [comment]
the issue is solved by removing `['main']` and `['rule']` and change ` result={}` into  `result=[].`
Thank you...
